services: 
  postgres: 
    image: postgres:14 
    container_name: postgres 
    environment: 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports: 
      - "5432:5432" 
    volumes: 
      - postgres:/var/lib/postgresql/data 
 
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    # environment:
    #   - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  # jenkins-runner:
  #   build:
  #     context: ./jenkins-runner
  #   container_name: jenkins-runner
  #   depends_on:
  #     - jenkins
  #   environment:
  #     JENKINS_URL: http://jenkins:8080
  #     JENKINS_AGENT_NAME: ansible-terraform-runner
  #     JENKINS_SECRET: ${JENKINS_SECRET} # Replace this with the actual secret key for the agent
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock # Allow the agent to run Docker commands

volumes: 
  postgres: 
    name: postgres
    driver: local 
  jenkins:
    name: jenkins
    driver: local
